version: '2.1'
services:
  bookstore-database:
    image: "postgres:9"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pingu123
      - POSTGRES_DB=bookstore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  bookstore-api:
    build: .
    depends_on:
      bookstore-database:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=bookstore-database
      - DB_USER=postgres
      - DB_PASSWORD=pingu123
      - DB_PORT=5432
    links:
      - "bookstore-database:bookstore-database"